# Generated by Django 4.0.3 on 2022-03-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='profile/')),
                ('logo_path', models.CharField(max_length=200)),
                ('profile_id', models.CharField(max_length=200)),
            ],
        ),
    ]
