# Generated by Django 4.0.3 on 2022-04-18 13:21

import cart.models
import cart.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Mobile incorrect.', regex='^\\+?1?\\d{9,15}$')])),
                ('otp', models.CharField(max_length=6)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ImageField(blank=True, storage=cart.storage.OverwriteStorage(), upload_to=cart.models.content_file_name)),
                ('profile_url', models.CharField(max_length=200)),
                ('profile_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField(default=10, verbose_name='Total amount')),
                ('add_amount', models.FloatField(default=0, verbose_name='Add amount')),
                ('deposit_cash', models.FloatField(default=0, verbose_name='Full Add amount')),
                ('win_amount', models.FloatField(default=0)),
                ('winning_cash', models.FloatField(default=0)),
                ('withdraw_amount', models.FloatField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_mobile', to='cart.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transcations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('winning_cash', models.FloatField(default=0)),
                ('insert_date_and_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.wallet')),
            ],
        ),
    ]
