# Generated by Django 4.0.3 on 2022-04-13 07:03

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, upload_to=cart.models.content_file_name),
        ),
    ]
