# Generated by Django 4.0.3 on 2022-04-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='insert_date_and_time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
