# Generated by Django 4.0.3 on 2022-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
