# Generated by Django 4.0.3 on 2022-03-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='2Vqhn6RW4Q', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(default='g4VFLMvdRh', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='sTdffkqO7Y', max_length=200),
        ),
    ]
