# Generated by Django 4.0.3 on 2022-03-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curr_available_amount_if_credit_row',
        ),
        migrations.RemoveField(
            model_name='user',
            name='debit_or_credit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hmac_or_checksum',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_method_record_unique_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='transaction_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet2store_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wallet_debit_record2wallet_credit_record',
        ),
    ]
