# Generated by Django 4.0.1 on 2022-04-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='current_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='add_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Add amount'),
        ),
    ]
