# Generated by Django 4.0.3 on 2022-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='wheels_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
