# Generated by Django 4.0.3 on 2022-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wallet_bonus_wallet_recieved_sreferral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referral_bonus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ticket_entry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
