# Generated by Django 4.0.3 on 2022-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_profile_user_profile_name_profile_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='gefjcHMaQ7', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_id',
            field=models.CharField(default='3uYIpWeAed', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='bXAY3HWpry', max_length=200),
        ),
    ]
