# Generated by Django 4.0.3 on 2022-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_user_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral',
            field=models.CharField(max_length=150),
        ),
    ]
