# Generated by Django 4.0.3 on 2022-04-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
