# Generated by Django 4.0.3 on 2022-03-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_user_curr_available_amount_if_credit_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
