# Generated by Django 4.0.3 on 2022-04-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_user_referral_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Bonus',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='Recieved_sreferral',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='referral_status',
        ),
        migrations.AddField(
            model_name='wallet',
            name='Bonus',
            field=models.FloatField(default=0),
        ),
    ]
