# Generated by Django 4.0.3 on 2022-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_wallet_referral_bonus_wallet_ticket_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Bonus',
            new_name='total_bonus_amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='referral_bonus',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='ticket_entry',
        ),
        migrations.AddField(
            model_name='transaction',
            name='Bonus',
            field=models.FloatField(default=0),
        ),
    ]
