# Generated by Django 4.0.3 on 2022-04-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='full_add_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Full Add amount'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='full_win_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
