# Generated by Django 4.0.3 on 2022-04-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_wallet_full_add_amount_wallet_full_win_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='full_add_amount',
            new_name='deposit_cash',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='full_win_amount',
            new_name='winning_cash',
        ),
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
