# Generated by Django 4.0.3 on 2022-04-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_wheel_wheels_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='wheels_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
