# Generated by Django 4.0.3 on 2022-04-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_logo_user_profile_url_alter_user_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='full_add_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Full Add amount'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='full_win_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='add_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Add amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_mobile', to='cart.user'),
        ),
    ]
