# Generated by Django 4.0.3 on 2022-04-25 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_bonus_wallet_total_bonus_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_url',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.IntegerField(blank=True, default=None, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('referral_url', models.CharField(blank=True, max_length=500, null=True)),
                ('referral_resource', models.CharField(blank=True, max_length=500, null=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_referred_by_user', to='cart.user')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_referral_user', to='cart.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
