# Generated by Django 4.0.3 on 2022-04-12 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_rename_full_add_amount_wallet_deposit_cash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='deduct_amount',
            new_name='withdraw_amount',
        ),
    ]
