# Generated by Django 4.0.3 on 2022-04-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_wallet_full_add_amount_wallet_full_win_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='full_add_amount',
            new_name='total_add_amount',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='full_win_amount',
            new_name='total_win_amount',
        ),
    ]
