# Generated by Django 4.0.3 on 2022-03-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_profile_name_alter_profile_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='logo',
        ),
    ]
