# Generated by Django 4.0.3 on 2022-04-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_userreferral_referral_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tranactiontype',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
