# Generated by Django 4.0.3 on 2022-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_rename_full_add_amount_wallet_total_add_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='add_amount',
            field=models.FloatField(default=0, verbose_name='Add amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_add_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Add amount'),
        ),
    ]
