# Generated by Django 4.0.3 on 2022-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_wallet_add_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='deduct_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_add_amount',
            field=models.FloatField(default=0, verbose_name='Total Add amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.FloatField(default=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_win_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='win_amount',
            field=models.FloatField(default=0),
        ),
    ]
