# Generated by Django 4.0.3 on 2022-04-12 13:10

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_profile_id_user_profile_url_user_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=cart.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, upload_to=cart.models.content_file_name),
        ),
    ]
