# Generated by Django 4.0.3 on 2022-04-26 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_wheel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tranactiontype',
            new_name='transactiontype',
        ),
    ]
