# Generated by Django 4.0.3 on 2022-04-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_wallet_deduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
