# Generated by Django 4.0.3 on 2022-04-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
