# Generated by Django 4.0.3 on 2022-04-13 17:58

import cart.models
import cart.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_wallet_deduct_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_dp',
            field=models.ImageField(blank=True, null=True, storage=cart.storage.OverwriteStorage(), upload_to=cart.models.content_file_name),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
