# Generated by Django 4.0.3 on 2022-04-14 09:21

import cart.models
import cart.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_wallet_deduct_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, storage=cart.storage.OverwriteStorage(), upload_to=cart.models.content_file_name),
        ),
    ]
