# Generated by Django 4.0.3 on 2022-03-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_user_logo_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
