# Generated by Django 4.0.3 on 2022-03-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_user_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
