# Generated by Django 4.0.3 on 2022-04-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_rename_profile_dp_user_profile_remove_user_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='amount'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
