# Generated by Django 4.0.3 on 2022-04-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_user_profile_url_alter_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='add_amount',
            field=models.FloatField(default=0, verbose_name='Add amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='deposit_cash',
            field=models.FloatField(default=0, verbose_name='Full Add amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='total_amount',
            field=models.FloatField(default=10, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='win_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='winning_cash',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='withdraw_amount',
            field=models.FloatField(default=0),
        ),
    ]
