# Generated by Django 4.0.3 on 2022-04-15 09:15

import cart.models
import cart.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_wallet_add_amount_alter_wallet_deposit_cash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default=1, storage=cart.storage.OverwriteStorage(), upload_to=cart.models.content_file_name),
            preserve_default=False,
        ),
    ]
