# Generated by Django 4.0.3 on 2022-04-17 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_transcations_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.wallet'),
            preserve_default=False,
        ),
    ]
