# Generated by Django 4.0.3 on 2022-04-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_transcations'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='winning_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
