# Generated by Django 4.0.3 on 2022-04-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_transcations_winning_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcations',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='transcations',
            name='winning_cash',
        ),
        migrations.AddField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='amount'),
        ),
    ]
