# Generated by Django 4.0.3 on 2022-04-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0020_remove_transcations_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
