# Generated by Django 4.0.3 on 2022-04-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_wallet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='winning_cash',
            field=models.FloatField(default=0),
        ),
    ]
