# Generated by Django 4.0.3 on 2022-04-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_transcations_winning_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='insert_date_and_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
