# Generated by Django 4.0.3 on 2022-04-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_transcations_insert_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='amount'),
        ),
    ]
