# Generated by Django 4.0.3 on 2022-04-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0025_alter_transcations_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcations',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user'),
        ),
    ]
