# Generated by Django 4.0.3 on 2022-04-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_alter_transcations_insert_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referral',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
