# Generated by Django 4.0.3 on 2022-04-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_wallet_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='referral_status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
