# Generated by Django 4.0.3 on 2022-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_wallet_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='referral',
            new_name='Recieved_sreferral',
        ),
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
