# Generated by Django 4.0.3 on 2022-04-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_transaction_userreferral_wheel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Bonus',
        ),
        migrations.AddField(
            model_name='wallet',
            name='Bonus',
            field=models.FloatField(default=0),
        ),
    ]
