# Generated by Django 4.0.3 on 2022-04-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_remove_transaction_bonus_wallet_bonus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wheel',
            old_name='wheels_list',
            new_name='wheels_index',
        ),
    ]
