# Generated by Django 4.0.3 on 2022-04-26 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_rename_wheels_list_wheel_wheels_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='wheel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.user'),
        ),
    ]
